# Generated by Django 5.0.1 on 2024-01-24 12:55

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_fishcard_answer_alter_fishcard_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcard',
            name='answer',
            field=main.utils.CustomRichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='fishcard',
            name='question',
            field=main.utils.CustomRichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='fishcardset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.set_file_name),
        ),
    ]
