# Generated by Django 5.0.1 on 2024-01-24 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fishcard_answer_alter_fishcard_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fishcardset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fishcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_answered', 'Not Answered'), ('correct', 'Correct'), ('semi_correct', 'Semi Correct'), ('wrong', 'Wrong')], default='not_answered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fishcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fishcard')),
                ('usertry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertry')),
            ],
        ),
    ]
