# Generated by Django 5.0.1 on 2024-01-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usertry_usertrycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcard',
            name='fishcardset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fishcardset'),
        ),
    ]
